services:
  local_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: provve
      POSTGRES_PASSWORD: 1
    volumes:
      - db:/var/lib/postgresql

volumes:
  db: