[versions]
junit = '6.0.2'
s3 = '2.2'
vertx = '4.5.24'
flyway = '11.20.2'
jooq = '3.20.11'
mapstruct = '1.6.3'
provve-backend = '0.0.1'
testcontainers = '2.0.2'
avaje = '12.3'
avaje-config = '5.0'
simple-java-mail = '8.12.6'
testcontainers-mailpit = '1.2.0'
jjwt = '0.13.0'

[libraries]
antifraud-api = { group = 'tech.provve.specs', name = 'antifraud-api', version.ref = 'provve-backend' }
argon2 = { module = 'de.mkammerer:argon2-jvm', version = '2.12' }

vertx-core = { module = 'io.vertx:vertx-core', version.ref = 'vertx' }
vertx-auth-jwt = { module = 'io.vertx:vertx-auth-jwt', version.ref = 'vertx' }
vertx-web = { module = 'io.vertx:vertx-web', version.ref = 'vertx' }
vertx-web-open-api = { module = 'io.vertx:vertx-web-openapi', version.ref = 'vertx' }

jackson-databind = { module = 'com.fasterxml.jackson.core:jackson-databind', version = '2.20.1' }
lombok = { group = 'org.projectlombok', name = 'lombok', version = '1.18.42' }
slf4j = { group = 'org.slf4j', name = 'slf4j-api', version = '2.1.0-alpha1' }
simple-mail = { module = 'org.simplejavamail:simple-java-mail', version.ref = 'simple-java-mail' }

jjwt-api = { module = 'io.jsonwebtoken:jjwt-api', version.ref = 'jjwt' }
jjwt-impl = { module = 'io.jsonwebtoken:jjwt-impl', version.ref = 'jjwt' }
jjwt-jackson = { module = 'io.jsonwebtoken:jjwt-jackson', version.ref = 'jjwt' }

avaje = { module = 'io.avaje:avaje-inject', version.ref = 'avaje' }
avaje-generator = { module = 'io.avaje:avaje-inject-generator', version.ref = 'avaje' }
avaje-test = { module = 'io.avaje:avaje-inject-test', version.ref = 'avaje' }
avaje-config = { module = 'io.avaje:avaje-config', version.ref = 'avaje-config' }

mockito-core = { module = 'org.mockito:mockito-core', version = '5.21.0' }
assertj = { module = 'org.assertj:assertj-core', version = '3.27.6' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'junit' }
junit-platform-launcher = { module = 'org.junit.platform:junit-platform-launcher', version.ref = 'junit' }
testcontainers-postgresql = { module = 'org.testcontainers:testcontainers-postgresql', version.ref = 'testcontainers' }
testcontainers-junit = { module = 'org.testcontainers:testcontainers-junit-jupiter', version.ref = 'testcontainers' }
testcontainers-mailpit = { group = 'ch.martinelli.oss', name = 'testcontainers-mailpit', version.ref = 'testcontainers-mailpit' }
local-s3-jupiter = { module = 'io.github.robothy:local-s3-jupiter', version.ref = 's3' }
local-s3-rest = { module = 'io.github.robothy:local-s3-rest', version.ref = 's3' }
amazon-s3 = { module = 'software.amazon.awssdk:s3', version = '2.41.21' }

hibernate-validation = { group = 'org.hibernate.validator', name = 'hibernate-validator', version = '9.1.0.Final' }
expressly = { group = 'org.glassfish.expressly', name = 'expressly', version = '6.0.0' }
flyway-postgres = { module = 'org.flywaydb:flyway-database-postgresql', version.ref = 'flyway' }
jooq-postgres = { group = 'org.jooq', name = 'jooq-postgres-extensions', version.ref = 'jooq' }
jooq = { group = 'org.jooq', name = 'jooq', version.ref = 'jooq' }
mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref = 'mapstruct' }
mapstruct = { module = 'org.mapstruct:mapstruct', version.ref = 'mapstruct' }

provve-api-dto = { module = 'tech.provve.api:server-dto', version = '0.0.1' }


[bundles]
testing = [
    'junit-jupiter',
    'junit-platform-launcher',
    'assertj'
]
vertx = [
    'vertx-web',
    'vertx-core',
    'vertx-auth-jwt',
    'vertx-web-open-api'
]
jjwt = [
    'jjwt-api',
    'jjwt-impl',
    'jjwt-jackson'
]


[plugins]
openapi-generator = { id = 'org.openapi.generator', version = '7.18.0' }
shadow = { id = 'com.gradleup.shadow', version = '9.3.1' }
flyway = { id = 'org.flywaydb.flyway', version.ref = 'flyway' }
jooq = { id = 'org.jooq.jooq-codegen-gradle', version.ref = 'jooq' }
dependencycheck = { id = 'org.owasp.dependencycheck', version = '12.2.0' }